loopback_users.guest = false
management.load_definitions = /etc/rabbitmq/definitions.json
prometheus.return_per_object_metrics = true
log.console = true
log.console.level = info
log.file = false
vm_memory_high_watermark.relative = 0.4
consumer_timeout = 1800000
